// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.PhysX.Immediate
{
    [StructLayout(LayoutKind.Explicit, Size = 360)]
    public unsafe partial struct PxFeatherstoneArticulationLinkData
    {
        [FieldOffset(0)] public PxMutableLinkData Base;

        [DllImport("Mochi.PhysX.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper40", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(PxFeatherstoneArticulationLinkData* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Constructor()
        {
            fixed (PxFeatherstoneArticulationLinkData* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [DllImport("Mochi.PhysX.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?initData@PxFeatherstoneArticulationLinkData@immediate@physx@@QEAAXXZ", ExactSpelling = true)]
        private static extern void initData_PInvoke(PxFeatherstoneArticulationLinkData* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void initData()
        {
            fixed (PxFeatherstoneArticulationLinkData* @this = &this)
            { initData_PInvoke(@this); }
        }

        [FieldOffset(36)] public PxFeatherstoneArticulationJointData inboundJoint;

        [FieldOffset(320)] public PxTransform pose;

        [FieldOffset(352)] public ulong parent;
    }
}
