// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using PhysX.Infrastructure;
using System.Runtime.InteropServices;

namespace PhysX.Immediate
{
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe partial struct PxImmediateConstraint
    {
        [FieldOffset(0)] public delegate* unmanaged[Cdecl]<Px1DConstraint*, PxVec3*, uint, PxConstraintInvMassScale*, void*, PxTransform*, PxTransform*, NativeBoolean, PxVec3*, PxVec3*, uint> prep;

        [FieldOffset(8)] public void* constantBlock;
    }
}
