// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

namespace Mochi.PhysX.Immediate
{
    [StructLayout(LayoutKind.Explicit, Size = 1)]
    public unsafe partial struct PxFeatherstoneArticulationData
    {
        [FieldOffset(0)] public PxArticulationFlags flags;
    }
}
