// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace Mochi.PhysX
{
    public enum PxAllocId
    {
        UNASSIGNED,
        APEX,
        PARTICLES,
        GPU_UTIL,
        CLOTH,
        NUM_IDS
    }
}
