// This file was automatically generated by Biohazrd and should not be modified by hand!
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 8)]
public unsafe partial struct PxAllocatorCallback
{
    public unsafe void Destructor()
    {
        fixed (PxAllocatorCallback* @this = &this)
        { VirtualMethodTablePointer->__DeletingDestructorPointer(@this); }
    }

    public unsafe void* allocate(ulong size, byte* typeName, byte* filename, int line)
    {
        fixed (PxAllocatorCallback* @this = &this)
        { return VirtualMethodTablePointer->allocate(@this, size, typeName, filename, line); }
    }

    public unsafe void deallocate(void* ptr)
    {
        fixed (PxAllocatorCallback* @this = &this)
        { VirtualMethodTablePointer->deallocate(@this, ptr); }
    }


    [FieldOffset(0)] public VirtualMethodTable* VirtualMethodTablePointer;

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct VirtualMethodTable
    {
        /// <summary>Virtual method pointer for `~PxAllocatorCallback`</summary>
        public delegate* unmanaged[Cdecl]<PxAllocatorCallback*, void> __DeletingDestructorPointer;
        /// <summary>Virtual method pointer for `allocate`</summary>
        public delegate* unmanaged[Cdecl]<PxAllocatorCallback*, ulong, byte*, byte*, int, void*> allocate;
        /// <summary>Virtual method pointer for `deallocate`</summary>
        public delegate* unmanaged[Cdecl]<PxAllocatorCallback*, void*, void> deallocate;
    }
}
