// This file was automatically generated by Biohazrd and should not be modified by hand!
using System;

[Flags]
public enum PxArticulationFlags : byte
{
    eFIX_BASE = 1,
    eDRIVE_LIMITS_ARE_FORCES = 2
}
