// This file was automatically generated by Biohazrd and should not be modified by hand!
using System;

[Flags]
public enum PxArticulationMotions : byte
{
    eLOCKED = 0,
    eLIMITED = 1,
    eFREE = 2
}
