// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace Mochi.PhysX
{
    public enum PxBatchQueryStatus
    {
        ePENDING = 0,
        eSUCCESS,
        eOVERFLOW
    }
}
