// This file was automatically generated by Biohazrd and should not be modified by hand!
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 8)]
public unsafe partial struct PxBoxController
{
    [FieldOffset(0)] public PxController Base;

    public unsafe float getHalfHeight()
    {
        fixed (PxBoxController* @this = &this)
        { return VirtualMethodTablePointer->getHalfHeight(@this); }
    }

    public unsafe float getHalfSideExtent()
    {
        fixed (PxBoxController* @this = &this)
        { return VirtualMethodTablePointer->getHalfSideExtent(@this); }
    }

    public unsafe float getHalfForwardExtent()
    {
        fixed (PxBoxController* @this = &this)
        { return VirtualMethodTablePointer->getHalfForwardExtent(@this); }
    }

    public unsafe bool setHalfHeight(float halfHeight)
    {
        fixed (PxBoxController* @this = &this)
        { return VirtualMethodTablePointer->setHalfHeight(@this, halfHeight); }
    }

    public unsafe bool setHalfSideExtent(float halfSideExtent)
    {
        fixed (PxBoxController* @this = &this)
        { return VirtualMethodTablePointer->setHalfSideExtent(@this, halfSideExtent); }
    }

    public unsafe bool setHalfForwardExtent(float halfForwardExtent)
    {
        fixed (PxBoxController* @this = &this)
        { return VirtualMethodTablePointer->setHalfForwardExtent(@this, halfForwardExtent); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxBoxController@physx@@IEAA@XZ", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(PxBoxController* @this);

    public unsafe void Constructor()
    {
        fixed (PxBoxController* @this = &this)
        { Constructor_PInvoke(@this); }
    }

    public unsafe void Destructor()
    {
        fixed (PxBoxController* @this = &this)
        { VirtualMethodTablePointer->__DeletingDestructorPointer(@this); }
    }


    [FieldOffset(0)] public VirtualMethodTable* VirtualMethodTablePointer;

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct VirtualMethodTable
    {
        /// <summary>Virtual method pointer for `getType`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, PxControllerShapeType> getType;
        /// <summary>Virtual method pointer for `release`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, void> release;
        /// <summary>Virtual method pointer for `move`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, PxVec3*, float, float, PxControllerFilters*, PxObstacleContext*, PxControllerCollisionFlags> move;
        /// <summary>Virtual method pointer for `setPosition`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, PxExtendedVec3*, bool> setPosition;
        /// <summary>Virtual method pointer for `getPosition`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, PxExtendedVec3*> getPosition;
        /// <summary>Virtual method pointer for `setFootPosition`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, PxExtendedVec3*, bool> setFootPosition;
        /// <summary>Virtual method pointer for `getFootPosition`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, out PxExtendedVec3, void> getFootPosition;
        /// <summary>Virtual method pointer for `getActor`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, PxRigidDynamic*> getActor;
        /// <summary>Virtual method pointer for `setStepOffset`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, float, void> setStepOffset;
        /// <summary>Virtual method pointer for `getStepOffset`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, float> getStepOffset;
        /// <summary>Virtual method pointer for `setNonWalkableMode`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, PxControllerNonWalkableMode, void> setNonWalkableMode;
        /// <summary>Virtual method pointer for `getNonWalkableMode`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, PxControllerNonWalkableMode> getNonWalkableMode;
        /// <summary>Virtual method pointer for `getContactOffset`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, float> getContactOffset;
        /// <summary>Virtual method pointer for `setContactOffset`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, float, void> setContactOffset;
        /// <summary>Virtual method pointer for `getUpDirection`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, out PxVec3, void> getUpDirection;
        /// <summary>Virtual method pointer for `setUpDirection`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, PxVec3*, void> setUpDirection;
        /// <summary>Virtual method pointer for `getSlopeLimit`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, float> getSlopeLimit;
        /// <summary>Virtual method pointer for `setSlopeLimit`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, float, void> setSlopeLimit;
        /// <summary>Virtual method pointer for `invalidateCache`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, void> invalidateCache;
        /// <summary>Virtual method pointer for `getScene`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, PxScene*> getScene;
        /// <summary>Virtual method pointer for `getUserData`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, void*> getUserData;
        /// <summary>Virtual method pointer for `setUserData`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, void*, void> setUserData;
        /// <summary>Virtual method pointer for `getState`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, PxControllerState*, void> getState;
        /// <summary>Virtual method pointer for `getStats`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, PxControllerStats*, void> getStats;
        /// <summary>Virtual method pointer for `resize`</summary>
        public delegate* unmanaged[Cdecl]<PxController*, float, void> resize;
        /// <summary>Virtual method pointer for `~PxBoxController`</summary>
        public delegate* unmanaged[Cdecl]<PxBoxController*, void> __DeletingDestructorPointer;
        /// <summary>Virtual method pointer for `getHalfHeight`</summary>
        public delegate* unmanaged[Cdecl]<PxBoxController*, float> getHalfHeight;
        /// <summary>Virtual method pointer for `getHalfSideExtent`</summary>
        public delegate* unmanaged[Cdecl]<PxBoxController*, float> getHalfSideExtent;
        /// <summary>Virtual method pointer for `getHalfForwardExtent`</summary>
        public delegate* unmanaged[Cdecl]<PxBoxController*, float> getHalfForwardExtent;
        /// <summary>Virtual method pointer for `setHalfHeight`</summary>
        public delegate* unmanaged[Cdecl]<PxBoxController*, float, bool> setHalfHeight;
        /// <summary>Virtual method pointer for `setHalfSideExtent`</summary>
        public delegate* unmanaged[Cdecl]<PxBoxController*, float, bool> setHalfSideExtent;
        /// <summary>Virtual method pointer for `setHalfForwardExtent`</summary>
        public delegate* unmanaged[Cdecl]<PxBoxController*, float, bool> setHalfForwardExtent;
    }
}
