// This file was automatically generated by Biohazrd and should not be modified by hand!
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 152)]
public unsafe partial struct PxCapsuleControllerDesc
{
    [FieldOffset(0)] public PxControllerDesc Base;

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxCapsuleControllerDesc@physx@@QEAA@XZ", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(PxCapsuleControllerDesc* @this);

    public unsafe void Constructor()
    {
        fixed (PxCapsuleControllerDesc* @this = &this)
        { Constructor_PInvoke(@this); }
    }

    public unsafe void Destructor()
    {
        fixed (PxCapsuleControllerDesc* @this = &this)
        { VirtualMethodTablePointer->__DeletingDestructorPointer(@this); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxCapsuleControllerDesc@physx@@QEAA@AEBV01@@Z", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(PxCapsuleControllerDesc* @this, PxCapsuleControllerDesc* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter);

    public unsafe void Constructor(PxCapsuleControllerDesc* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter)
    {
        fixed (PxCapsuleControllerDesc* @this = &this)
        { Constructor_PInvoke(@this, __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??4PxCapsuleControllerDesc@physx@@QEAAAEAV01@AEBV01@@Z", ExactSpelling = true)]
    private static extern PxCapsuleControllerDesc* operator_Equal_PInvoke(PxCapsuleControllerDesc* @this, PxCapsuleControllerDesc* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter);

    public unsafe PxCapsuleControllerDesc* operator_Equal(PxCapsuleControllerDesc* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter)
    {
        fixed (PxCapsuleControllerDesc* @this = &this)
        { return operator_Equal_PInvoke(@this, __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter); }
    }

    public unsafe void setToDefault()
    {
        fixed (PxCapsuleControllerDesc* @this = &this)
        { VirtualMethodTablePointer->setToDefault(@this); }
    }

    public unsafe bool isValid()
    {
        fixed (PxCapsuleControllerDesc* @this = &this)
        { return VirtualMethodTablePointer->isValid(@this); }
    }

    [FieldOffset(136)] public float radius;

    [FieldOffset(140)] public float height;

    [FieldOffset(144)] public PxCapsuleClimbingMode climbingMode;

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?copy@PxCapsuleControllerDesc@physx@@IEAAXAEBV12@@Z", ExactSpelling = true)]
    private static extern void copy_PInvoke(PxCapsuleControllerDesc* @this, PxCapsuleControllerDesc* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter);

    public unsafe void copy(PxCapsuleControllerDesc* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter)
    {
        fixed (PxCapsuleControllerDesc* @this = &this)
        { copy_PInvoke(@this, __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter); }
    }


    [FieldOffset(0)] public VirtualMethodTable* VirtualMethodTablePointer;

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct VirtualMethodTable
    {
        /// <summary>Virtual method pointer for `isValid`</summary>
        public delegate* unmanaged[Cdecl]<PxCapsuleControllerDesc*, bool> isValid;
        /// <summary>Virtual method pointer for `~PxCapsuleControllerDesc`</summary>
        public delegate* unmanaged[Cdecl]<PxCapsuleControllerDesc*, void> __DeletingDestructorPointer;
        /// <summary>Virtual method pointer for `setToDefault`</summary>
        public delegate* unmanaged[Cdecl]<PxCapsuleControllerDesc*, void> setToDefault;
    }
}
