// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace Mochi.PhysX
{
    public enum PxControllerShapeType
    {
        eBOX,
        eCAPSULE,
        eFORCE_DWORD = 0x7FFFFFFF
    }
}
