// This file was automatically generated by Biohazrd and should not be modified by hand!
public enum PxConstraintSolveHint
{
    eNONE = 0,
    eACCELERATION1 = 256,
    eSLERP_SPRING = 258,
    eACCELERATION2 = 512,
    eACCELERATION3 = 768,
    eROTATIONAL_EQUALITY = 1024,
    eROTATIONAL_INEQUALITY = 1025,
    eEQUALITY = 2048,
    eINEQUALITY = 2049
}
