// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using Mochi.PhysX.Infrastructure;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.PhysX
{
    [StructLayout(LayoutKind.Explicit, Size = 48)]
    public unsafe partial struct PxContactPairHeader
    {
        [DllImport("Mochi.PhysX.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper139", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(PxContactPairHeader* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Constructor()
        {
            fixed (PxContactPairHeader* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [FieldOffset(0)] public ConstantArray_physx__UNICODE_003A____UNICODE_003A__PxRigidActor__UNICODE_0020____UNICODE_002A___2 actors;

        [FieldOffset(16)] public byte* extraDataStream;

        [FieldOffset(24)] public ushort extraDataStreamSize;

        [FieldOffset(26)] public PxContactPairHeaderFlags flags;

        [FieldOffset(32)] public PxContactPair* pairs;

        [FieldOffset(40)] public uint nbPairs;
    }
}
