// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.PhysX
{
    [StructLayout(LayoutKind.Explicit, Size = 4)]
    public unsafe partial struct PxContactPairIndex
    {
        [FieldOffset(0)] public PxContactPairExtraDataItem Base;

        [DllImport("Mochi.PhysX.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper137", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(PxContactPairIndex* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Constructor()
        {
            fixed (PxContactPairIndex* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [FieldOffset(2)] public ushort index;
    }
}
