// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace PhysX
{
    public enum PxCombineMode
    {
        eAVERAGE = 0,
        eMIN = 1,
        eMULTIPLY = 2,
        eMAX = 3,
        eN_VALUES = 4,
        ePAD_32 = 0x7FFFFFFF
    }
}
