// This file was automatically generated by Biohazrd and should not be modified by hand!
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 80)]
public unsafe partial struct PxConvexMeshDesc
{
    [FieldOffset(0)] public PxBoundedData points;

    [FieldOffset(24)] public PxBoundedData polygons;

    [FieldOffset(48)] public PxBoundedData indices;

    [FieldOffset(72)] public PxConvexFlags flags;

    [FieldOffset(74)] public ushort vertexLimit;

    [FieldOffset(76)] public ushort quantizedCount;

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxConvexMeshDesc@physx@@QEAA@XZ", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(PxConvexMeshDesc* @this);

    public unsafe void Constructor()
    {
        fixed (PxConvexMeshDesc* @this = &this)
        { Constructor_PInvoke(@this); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?setToDefault@PxConvexMeshDesc@physx@@QEAAXXZ", ExactSpelling = true)]
    private static extern void setToDefault_PInvoke(PxConvexMeshDesc* @this);

    public unsafe void setToDefault()
    {
        fixed (PxConvexMeshDesc* @this = &this)
        { setToDefault_PInvoke(@this); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?isValid@PxConvexMeshDesc@physx@@QEBA_NXZ", ExactSpelling = true)]
    [return: MarshalAs(UnmanagedType.I1)]
    private static extern bool isValid_PInvoke(PxConvexMeshDesc* @this);

    public unsafe bool isValid()
    {
        fixed (PxConvexMeshDesc* @this = &this)
        { return isValid_PInvoke(@this); }
    }
}
