// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System;

namespace PhysX
{
    [Flags]
    public enum PxContactPairFlags : ushort
    {
        eREMOVED_SHAPE_0 = 1,
        eREMOVED_SHAPE_1 = 2,
        eACTOR_PAIR_HAS_FIRST_TOUCH = 4,
        eACTOR_PAIR_LOST_TOUCH = 8,
        eINTERNAL_HAS_IMPULSES = 16,
        eINTERNAL_CONTACTS_ARE_FLIPPED = 32
    }
}
