// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace Mochi.PhysX
{
    public enum PxConstraintExtIDs
    {
        eJOINT,
        eVEHICLE_SUSP_LIMIT,
        eVEHICLE_STICKY_TYRE,
        eNEXT_FREE_ID,
        eINVALID_ID = 0x7FFFFFFF
    }
}
