// This file was automatically generated by Biohazrd and should not be modified by hand!
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 136)]
public unsafe partial struct PxControllerDesc
{
    public unsafe bool isValid()
    {
        fixed (PxControllerDesc* @this = &this)
        { return VirtualMethodTablePointer->isValid(@this); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?getType@PxControllerDesc@physx@@QEBA?AW4Enum@PxControllerShapeType@2@XZ", ExactSpelling = true)]
    private static extern PxControllerShapeType getType_PInvoke(PxControllerDesc* @this);

    public unsafe PxControllerShapeType getType()
    {
        fixed (PxControllerDesc* @this = &this)
        { return getType_PInvoke(@this); }
    }

    [FieldOffset(8)] public PxExtendedVec3 position;

    [FieldOffset(32)] public PxVec3 upDirection;

    [FieldOffset(44)] public float slopeLimit;

    [FieldOffset(48)] public float invisibleWallHeight;

    [FieldOffset(52)] public float maxJumpHeight;

    [FieldOffset(56)] public float contactOffset;

    [FieldOffset(60)] public float stepOffset;

    [FieldOffset(64)] public float density;

    [FieldOffset(68)] public float scaleCoeff;

    [FieldOffset(72)] public float volumeGrowth;

    [FieldOffset(80)] public PxUserControllerHitReport* reportCallback;

    [FieldOffset(88)] public PxControllerBehaviorCallback* behaviorCallback;

    [FieldOffset(96)] public PxControllerNonWalkableMode nonWalkableMode;

    [FieldOffset(104)] public PxMaterial* material;

    [FieldOffset(112)] [MarshalAs(UnmanagedType.I1)] public bool registerDeletionListener;

    [FieldOffset(120)] public void* userData;

    [FieldOffset(128)] public PxControllerShapeType mType;

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxControllerDesc@physx@@IEAA@W4Enum@PxControllerShapeType@1@@Z", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(PxControllerDesc* @this, PxControllerShapeType __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter);

    public unsafe void Constructor(PxControllerShapeType __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter)
    {
        fixed (PxControllerDesc* @this = &this)
        { Constructor_PInvoke(@this, __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter); }
    }

    public unsafe void Destructor()
    {
        fixed (PxControllerDesc* @this = &this)
        { VirtualMethodTablePointer->__DeletingDestructorPointer(@this); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxControllerDesc@physx@@IEAA@AEBV01@@Z", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(PxControllerDesc* @this, PxControllerDesc* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter);

    public unsafe void Constructor(PxControllerDesc* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter)
    {
        fixed (PxControllerDesc* @this = &this)
        { Constructor_PInvoke(@this, __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??4PxControllerDesc@physx@@IEAAAEAV01@AEBV01@@Z", ExactSpelling = true)]
    private static extern PxControllerDesc* operator_Equal_PInvoke(PxControllerDesc* @this, PxControllerDesc* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter);

    public unsafe PxControllerDesc* operator_Equal(PxControllerDesc* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter)
    {
        fixed (PxControllerDesc* @this = &this)
        { return operator_Equal_PInvoke(@this, __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?copy@PxControllerDesc@physx@@IEAAXAEBV12@@Z", ExactSpelling = true)]
    private static extern void copy_PInvoke(PxControllerDesc* @this, PxControllerDesc* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter);

    public unsafe void copy(PxControllerDesc* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter)
    {
        fixed (PxControllerDesc* @this = &this)
        { copy_PInvoke(@this, __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter); }
    }


    [FieldOffset(0)] public VirtualMethodTable* VirtualMethodTablePointer;

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct VirtualMethodTable
    {
        /// <summary>Virtual method pointer for `isValid`</summary>
        public delegate* unmanaged[Cdecl]<PxControllerDesc*, NativeBoolean> isValid;
        /// <summary>Virtual method pointer for `~PxControllerDesc`</summary>
        public delegate* unmanaged[Cdecl]<PxControllerDesc*, void> __DeletingDestructorPointer;
    }
}
