// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace PhysX
{
    public enum PxCudaInteropMode
    {
        NO_INTEROP = 0,
        D3D10_INTEROP,
        D3D11_INTEROP,
        OGL_INTEROP,
        COUNT
    }
}
