// This file was automatically generated by Biohazrd and should not be modified by hand!
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 16)]
public unsafe partial struct PxD6JointDrive
{
    [FieldOffset(0)] public PxSpring Base;

    [FieldOffset(8)] public float forceLimit;

    [FieldOffset(12)] public PxD6JointDriveFlags flags;

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxD6JointDrive@physx@@QEAA@XZ", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(PxD6JointDrive* @this);

    public unsafe void Constructor()
    {
        fixed (PxD6JointDrive* @this = &this)
        { Constructor_PInvoke(@this); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxD6JointDrive@physx@@QEAA@MMM_N@Z", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(PxD6JointDrive* @this, float driveStiffness, float driveDamping, float driveForceLimit, bool isAcceleration);

    public unsafe void Constructor(float driveStiffness, float driveDamping, float driveForceLimit, bool isAcceleration = false)
    {
        fixed (PxD6JointDrive* @this = &this)
        { Constructor_PInvoke(@this, driveStiffness, driveDamping, driveForceLimit, isAcceleration); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?isValid@PxD6JointDrive@physx@@QEBA_NXZ", ExactSpelling = true)]
    private static extern bool isValid_PInvoke(PxD6JointDrive* @this);

    public unsafe bool isValid()
    {
        fixed (PxD6JointDrive* @this = &this)
        { return isValid_PInvoke(@this); }
    }
}
