// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System;

namespace PhysX
{
    [Flags]
    public enum PxDataAccessFlags : byte
    {
        eREADABLE = 1,
        eWRITABLE = 2,
        eDEVICE = 4
    }
}
