// This file was automatically generated by Biohazrd and should not be modified by hand!
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 32)]
public unsafe partial struct PxDefaultMemoryOutputStream
{
    [FieldOffset(0)] public PxOutputStream Base;

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxDefaultMemoryOutputStream@physx@@QEAA@AEAVPxAllocatorCallback@1@@Z", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(PxDefaultMemoryOutputStream* @this, PxAllocatorCallback* allocator);

    public unsafe void Constructor(PxAllocatorCallback* allocator)
    {
        fixed (PxDefaultMemoryOutputStream* @this = &this)
        { Constructor_PInvoke(@this, allocator); }
    }

    public unsafe void Destructor()
    {
        fixed (PxDefaultMemoryOutputStream* @this = &this)
        { VirtualMethodTablePointer->__DeletingDestructorPointer(@this); }
    }

    public unsafe uint write(void* src, uint count)
    {
        fixed (PxDefaultMemoryOutputStream* @this = &this)
        { return VirtualMethodTablePointer->write(@this, src, count); }
    }

    public unsafe uint getSize()
    {
        fixed (PxDefaultMemoryOutputStream* @this = &this)
        { return VirtualMethodTablePointer->getSize(@this); }
    }

    public unsafe byte* getData()
    {
        fixed (PxDefaultMemoryOutputStream* @this = &this)
        { return VirtualMethodTablePointer->getData(@this); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxDefaultMemoryOutputStream@physx@@AEAA@AEBV01@@Z", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(PxDefaultMemoryOutputStream* @this, PxDefaultMemoryOutputStream* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter);

    public unsafe void Constructor(PxDefaultMemoryOutputStream* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter)
    {
        fixed (PxDefaultMemoryOutputStream* @this = &this)
        { Constructor_PInvoke(@this, __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??4PxDefaultMemoryOutputStream@physx@@AEAAAEAV01@AEBV01@@Z", ExactSpelling = true)]
    private static extern PxDefaultMemoryOutputStream* operator_Equal_PInvoke(PxDefaultMemoryOutputStream* @this, PxDefaultMemoryOutputStream* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter);

    public unsafe PxDefaultMemoryOutputStream* operator_Equal(PxDefaultMemoryOutputStream* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter)
    {
        fixed (PxDefaultMemoryOutputStream* @this = &this)
        { return operator_Equal_PInvoke(@this, __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter); }
    }

    [FieldOffset(8)] public PxAllocatorCallback* mAllocator;

    [FieldOffset(16)] public byte* mData;

    [FieldOffset(24)] public uint mSize;

    [FieldOffset(28)] public uint mCapacity;


    [FieldOffset(0)] public VirtualMethodTable* VirtualMethodTablePointer;

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct VirtualMethodTable
    {
        /// <summary>Virtual method pointer for `write`</summary>
        public delegate* unmanaged[Cdecl]<PxDefaultMemoryOutputStream*, void*, uint, uint> write;
        /// <summary>Virtual method pointer for `~PxDefaultMemoryOutputStream`</summary>
        public delegate* unmanaged[Cdecl]<PxDefaultMemoryOutputStream*, void> __DeletingDestructorPointer;
        /// <summary>Virtual method pointer for `getSize`</summary>
        public delegate* unmanaged[Cdecl]<PxDefaultMemoryOutputStream*, uint> getSize;
        /// <summary>Virtual method pointer for `getData`</summary>
        public delegate* unmanaged[Cdecl]<PxDefaultMemoryOutputStream*, byte*> getData;
    }
}
