// This file was automatically generated by Biohazrd and should not be modified by hand!
using System;

[Flags]
public enum PxDeletionEventFlags : byte
{
    eUSER_RELEASE = 1,
    eMEMORY_RELEASE = 2
}
