// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

namespace PhysX
{
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public unsafe partial struct PxExtendedContact
    {
        [FieldOffset(0)] public PxContact Base;

        [FieldOffset(16)] public PxVec3 targetVelocity;

        [FieldOffset(28)] public float maxImpulse;
    }
}
