// This file was automatically generated by Biohazrd and should not be modified by hand!
public enum PxFilterOp
{
    PX_FILTEROP_AND,
    PX_FILTEROP_OR,
    PX_FILTEROP_XOR,
    PX_FILTEROP_NAND,
    PX_FILTEROP_NOR,
    PX_FILTEROP_NXOR,
    PX_FILTEROP_SWAP_AND
}
