// This file was automatically generated by Biohazrd and should not be modified by hand!
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 24)]
public unsafe partial struct PxJointLinearLimit
{
    [FieldOffset(0)] public PxJointLimitParameters Base;

    [FieldOffset(20)] public float value;

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxJointLinearLimit@physx@@QEAA@AEBVPxTolerancesScale@1@MM@Z", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(PxJointLinearLimit* @this, PxTolerancesScale* scale, float extent, float contactDist);

    public unsafe void Constructor(PxTolerancesScale* scale, float extent, float contactDist = -1f)
    {
        fixed (PxJointLinearLimit* @this = &this)
        { Constructor_PInvoke(@this, scale, extent, contactDist); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxJointLinearLimit@physx@@QEAA@MAEBVPxSpring@1@@Z", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(PxJointLinearLimit* @this, float extent, PxSpring* spring);

    public unsafe void Constructor(float extent, PxSpring* spring)
    {
        fixed (PxJointLinearLimit* @this = &this)
        { Constructor_PInvoke(@this, extent, spring); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?isValid@PxJointLinearLimit@physx@@QEBA_NXZ", ExactSpelling = true)]
    [return: MarshalAs(UnmanagedType.I1)]
    private static extern bool isValid_PInvoke(PxJointLinearLimit* @this);

    public unsafe bool isValid()
    {
        fixed (PxJointLinearLimit* @this = &this)
        { return isValid_PInvoke(@this); }
    }
}
