// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.PhysX
{
    [StructLayout(LayoutKind.Explicit, Size = 28)]
    public unsafe partial struct PxJointLinearLimitPair
    {
        [FieldOffset(0)] public PxJointLimitParameters Base;

        [FieldOffset(20)] public float upper;

        [FieldOffset(24)] public float lower;

        [DllImport("Mochi.PhysX.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper165", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(PxJointLinearLimitPair* @this, PxTolerancesScale* scale, float lowerLimit, float upperLimit, float contactDist);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public PxJointLinearLimitPair(PxTolerancesScale* scale, float lowerLimit = -1.13427449E+38f, float upperLimit = 1.13427449E+38f, float contactDist = -1f)
        {
            fixed (PxJointLinearLimitPair* @this = &this)
            { Constructor_PInvoke(@this, scale, lowerLimit, upperLimit, contactDist); }
        }

        [DllImport("Mochi.PhysX.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper166", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(PxJointLinearLimitPair* @this, float lowerLimit, float upperLimit, PxSpring* spring);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public PxJointLinearLimitPair(float lowerLimit, float upperLimit, PxSpring* spring)
        {
            fixed (PxJointLinearLimitPair* @this = &this)
            { Constructor_PInvoke(@this, lowerLimit, upperLimit, spring); }
        }

        [DllImport("Mochi.PhysX.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?isValid@PxJointLinearLimitPair@physx@@QEBA_NXZ", ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        private static extern bool isValid_PInvoke(PxJointLinearLimitPair* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool isValid()
        {
            fixed (PxJointLinearLimitPair* @this = &this)
            { return isValid_PInvoke(@this); }
        }
    }
}
