// This file was automatically generated by Biohazrd and should not be modified by hand!
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 16)]
public unsafe partial struct PxPackValidation
{
    [FieldOffset(0)] public byte _;

    [FieldOffset(8)] public long a;
}
