// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace PhysX
{
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe partial struct PxPlane
    {
        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxPlane@physx@@QEAA@XZ", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(PxPlane* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Constructor()
        {
            fixed (PxPlane* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxPlane@physx@@QEAA@MMMM@Z", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(PxPlane* @this, float nx, float ny, float nz, float distance);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Constructor(float nx, float ny, float nz, float distance)
        {
            fixed (PxPlane* @this = &this)
            { Constructor_PInvoke(@this, nx, ny, nz, distance); }
        }

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxPlane@physx@@QEAA@AEBVPxVec3@1@M@Z", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(PxPlane* @this, PxVec3* normal, float distance);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Constructor(PxVec3* normal, float distance)
        {
            fixed (PxPlane* @this = &this)
            { Constructor_PInvoke(@this, normal, distance); }
        }

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxPlane@physx@@QEAA@AEBVPxVec3@1@0@Z", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(PxPlane* @this, PxVec3* point, PxVec3* normal);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Constructor(PxVec3* point, PxVec3* normal)
        {
            fixed (PxPlane* @this = &this)
            { Constructor_PInvoke(@this, point, normal); }
        }

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxPlane@physx@@QEAA@AEBVPxVec3@1@00@Z", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(PxPlane* @this, PxVec3* p0, PxVec3* p1, PxVec3* p2);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Constructor(PxVec3* p0, PxVec3* p1, PxVec3* p2)
        {
            fixed (PxPlane* @this = &this)
            { Constructor_PInvoke(@this, p0, p1, p2); }
        }

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??8PxPlane@physx@@QEBA_NAEBV01@@Z", ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        private static extern bool operator_EqualEqual_PInvoke(PxPlane* @this, PxPlane* p);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe bool operator_EqualEqual(PxPlane* p)
        {
            fixed (PxPlane* @this = &this)
            { return operator_EqualEqual_PInvoke(@this, p); }
        }

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?distance@PxPlane@physx@@QEBAMAEBVPxVec3@2@@Z", ExactSpelling = true)]
        private static extern float distance_PInvoke(PxPlane* @this, PxVec3* p);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe float distance(PxVec3* p)
        {
            fixed (PxPlane* @this = &this)
            { return distance_PInvoke(@this, p); }
        }

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?contains@PxPlane@physx@@QEBA_NAEBVPxVec3@2@@Z", ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        private static extern bool contains_PInvoke(PxPlane* @this, PxVec3* p);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe bool contains(PxVec3* p)
        {
            fixed (PxPlane* @this = &this)
            { return contains_PInvoke(@this, p); }
        }

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?project@PxPlane@physx@@QEBA?AVPxVec3@2@AEBV32@@Z", ExactSpelling = true)]
        private static extern PxVec3* project_PInvoke(PxPlane* @this, out PxVec3 __returnBuffer, PxVec3* p);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe PxVec3 project(PxVec3* p)
        {
            fixed (PxPlane* @this = &this)
            {
                PxVec3 __returnBuffer;
                project_PInvoke(@this, out __returnBuffer, p);
                return __returnBuffer;
            }
        }

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?pointInPlane@PxPlane@physx@@QEBA?AVPxVec3@2@XZ", ExactSpelling = true)]
        private static extern PxVec3* pointInPlane_PInvoke(PxPlane* @this, out PxVec3 __returnBuffer);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe PxVec3 pointInPlane()
        {
            fixed (PxPlane* @this = &this)
            {
                PxVec3 __returnBuffer;
                pointInPlane_PInvoke(@this, out __returnBuffer);
                return __returnBuffer;
            }
        }

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?normalize@PxPlane@physx@@QEAAXXZ", ExactSpelling = true)]
        private static extern void normalize_PInvoke(PxPlane* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void normalize()
        {
            fixed (PxPlane* @this = &this)
            { normalize_PInvoke(@this); }
        }

        [FieldOffset(0)] public PxVec3 n;

        [FieldOffset(12)] public float d;
    }
}
