// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using PhysX.Infrastructure;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace PhysX
{
    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public unsafe partial struct PxProfilerCallback
    {
        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Destructor()
        {
            fixed (PxProfilerCallback* @this = &this)
            { VirtualMethodTablePointer->__DeletingDestructorPointer(@this); }
        }

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void* zoneStart(byte* eventName, bool detached, ulong contextId)
        {
            fixed (PxProfilerCallback* @this = &this)
            { return VirtualMethodTablePointer->zoneStart(@this, eventName, detached, contextId); }
        }

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void zoneEnd(void* profilerData, byte* eventName, bool detached, ulong contextId)
        {
            fixed (PxProfilerCallback* @this = &this)
            { VirtualMethodTablePointer->zoneEnd(@this, profilerData, eventName, detached, contextId); }
        }

        [FieldOffset(0)] public VirtualMethodTable* VirtualMethodTablePointer;

        [StructLayout(LayoutKind.Sequential)]
        public unsafe struct VirtualMethodTable
        {
            /// <summary>Virtual method pointer for `~PxProfilerCallback`</summary>
            public delegate* unmanaged[Cdecl]<PxProfilerCallback*, void> __DeletingDestructorPointer;
            /// <summary>Virtual method pointer for `zoneStart`</summary>
            public delegate* unmanaged[Cdecl]<PxProfilerCallback*, byte*, NativeBoolean, ulong, void*> zoneStart;
            /// <summary>Virtual method pointer for `zoneEnd`</summary>
            public delegate* unmanaged[Cdecl]<PxProfilerCallback*, void*, byte*, NativeBoolean, ulong, void> zoneEnd;
        }
    }
}
