// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System;

namespace PhysX
{
    [Flags]
    public enum PxPvdInstrumentationFlags : byte
    {
        eDEBUG = 1,
        ePROFILE = 2,
        eMEMORY = 4,
        eALL = 7
    }
}
