// This file was automatically generated by Biohazrd and should not be modified by hand!
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 8)]
public unsafe partial struct PxSceneWriteLock
{
    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxSceneWriteLock@physx@@AEAA@AEBV01@@Z", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(PxSceneWriteLock* @this, PxSceneWriteLock* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter);

    public unsafe void Constructor(PxSceneWriteLock* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter)
    {
        fixed (PxSceneWriteLock* @this = &this)
        { Constructor_PInvoke(@this, __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??4PxSceneWriteLock@physx@@AEAAAEAV01@AEBV01@@Z", ExactSpelling = true)]
    private static extern PxSceneWriteLock* operator_Equal_PInvoke(PxSceneWriteLock* @this, PxSceneWriteLock* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter);

    public unsafe PxSceneWriteLock* operator_Equal(PxSceneWriteLock* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter)
    {
        fixed (PxSceneWriteLock* @this = &this)
        { return operator_Equal_PInvoke(@this, __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxSceneWriteLock@physx@@QEAA@AEAVPxScene@1@PEBDI@Z", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(PxSceneWriteLock* @this, PxScene* scene, byte* file, uint line);

    public unsafe void Constructor(PxScene* scene, byte* file = null, uint line = 0)
    {
        fixed (PxSceneWriteLock* @this = &this)
        { Constructor_PInvoke(@this, scene, file, line); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??_DPxSceneWriteLock@physx@@QEAAXXZ", ExactSpelling = true)]
    private static extern void Destructor_PInvoke(PxSceneWriteLock* @this);

    public unsafe void Destructor()
    {
        fixed (PxSceneWriteLock* @this = &this)
        { Destructor_PInvoke(@this); }
    }

    [FieldOffset(0)] public PxScene* mScene;
}
