// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace PhysX
{
    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public unsafe partial struct PxSceneWriteLock
    {
        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxSceneWriteLock@physx@@AEAA@AEBV01@@Z", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(PxSceneWriteLock* @this, PxSceneWriteLock* arg0);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Constructor(PxSceneWriteLock* arg0)
        {
            fixed (PxSceneWriteLock* @this = &this)
            { Constructor_PInvoke(@this, arg0); }
        }

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??4PxSceneWriteLock@physx@@AEAAAEAV01@AEBV01@@Z", ExactSpelling = true)]
        private static extern PxSceneWriteLock* operator_Equal_PInvoke(PxSceneWriteLock* @this, PxSceneWriteLock* arg0);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe PxSceneWriteLock* operator_Equal(PxSceneWriteLock* arg0)
        {
            fixed (PxSceneWriteLock* @this = &this)
            { return operator_Equal_PInvoke(@this, arg0); }
        }

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxSceneWriteLock@physx@@QEAA@AEAVPxScene@1@PEBDI@Z", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(PxSceneWriteLock* @this, PxScene* scene, byte* file, uint line);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Constructor(PxScene* scene, byte* file = null, uint line = 0)
        {
            fixed (PxSceneWriteLock* @this = &this)
            { Constructor_PInvoke(@this, scene, file, line); }
        }

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??1PxSceneWriteLock@physx@@QEAA@XZ", ExactSpelling = true)]
        private static extern void Destructor_PInvoke(PxSceneWriteLock* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Destructor()
        {
            fixed (PxSceneWriteLock* @this = &this)
            { Destructor_PInvoke(@this); }
        }

        [FieldOffset(0)] public PxScene* mScene;
    }
}
