// This file was automatically generated by Biohazrd and should not be modified by hand!
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 8)]
public unsafe partial struct PxSerializer
{
    public unsafe byte* getConcreteTypeName()
    {
        fixed (PxSerializer* @this = &this)
        { return VirtualMethodTablePointer->getConcreteTypeName(@this); }
    }

    public unsafe void requiresObjects(PxBase* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter_0, PxProcessPxBaseCallback* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter_1)
    {
        fixed (PxSerializer* @this = &this)
        { VirtualMethodTablePointer->requiresObjects(@this, __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter_0, __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter_1); }
    }

    public unsafe bool isSubordinate()
    {
        fixed (PxSerializer* @this = &this)
        { return VirtualMethodTablePointer->isSubordinate(@this); }
    }

    public unsafe void exportExtraData(PxBase* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter_0, PxSerializationContext* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter_1)
    {
        fixed (PxSerializer* @this = &this)
        { VirtualMethodTablePointer->exportExtraData(@this, __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter_0, __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter_1); }
    }

    public unsafe void exportData(PxBase* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter_0, PxSerializationContext* __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter_1)
    {
        fixed (PxSerializer* @this = &this)
        { VirtualMethodTablePointer->exportData(@this, __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter_0, __UNICODE_003C____UNICODE_003E__UnnamedTranslatedParameter_1); }
    }

    public unsafe void registerReferences(PxBase* obj, PxSerializationContext* s)
    {
        fixed (PxSerializer* @this = &this)
        { VirtualMethodTablePointer->registerReferences(@this, obj, s); }
    }

    public unsafe ulong getClassSize()
    {
        fixed (PxSerializer* @this = &this)
        { return VirtualMethodTablePointer->getClassSize(@this); }
    }

    public unsafe PxBase* createObject(byte** address, PxDeserializationContext* context)
    {
        fixed (PxSerializer* @this = &this)
        { return VirtualMethodTablePointer->createObject(@this, address, context); }
    }

    public unsafe void Destructor()
    {
        fixed (PxSerializer* @this = &this)
        { VirtualMethodTablePointer->__DeletingDestructorPointer(@this); }
    }


    [FieldOffset(0)] public VirtualMethodTable* VirtualMethodTablePointer;

    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct VirtualMethodTable
    {
        /// <summary>Virtual method pointer for `getConcreteTypeName`</summary>
        public delegate* unmanaged[Cdecl]<PxSerializer*, byte*> getConcreteTypeName;
        /// <summary>Virtual method pointer for `requiresObjects`</summary>
        public delegate* unmanaged[Cdecl]<PxSerializer*, PxBase*, PxProcessPxBaseCallback*, void> requiresObjects;
        /// <summary>Virtual method pointer for `isSubordinate`</summary>
        public delegate* unmanaged[Cdecl]<PxSerializer*, bool> isSubordinate;
        /// <summary>Virtual method pointer for `exportExtraData`</summary>
        public delegate* unmanaged[Cdecl]<PxSerializer*, PxBase*, PxSerializationContext*, void> exportExtraData;
        /// <summary>Virtual method pointer for `exportData`</summary>
        public delegate* unmanaged[Cdecl]<PxSerializer*, PxBase*, PxSerializationContext*, void> exportData;
        /// <summary>Virtual method pointer for `registerReferences`</summary>
        public delegate* unmanaged[Cdecl]<PxSerializer*, PxBase*, PxSerializationContext*, void> registerReferences;
        /// <summary>Virtual method pointer for `getClassSize`</summary>
        public delegate* unmanaged[Cdecl]<PxSerializer*, ulong> getClassSize;
        /// <summary>Virtual method pointer for `createObject`</summary>
        public delegate* unmanaged[Cdecl]<PxSerializer*, byte**, PxDeserializationContext*, PxBase*> createObject;
        /// <summary>Virtual method pointer for `~PxSerializer`</summary>
        public delegate* unmanaged[Cdecl]<PxSerializer*, void> __DeletingDestructorPointer;
    }
}
