// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace PhysX
{
    [StructLayout(LayoutKind.Explicit, Size = 56)]
    public unsafe partial struct PxSimpleTriangleMesh
    {
        [FieldOffset(0)] public PxBoundedData points;

        [FieldOffset(24)] public PxBoundedData triangles;

        [FieldOffset(48)] public PxMeshFlags flags;

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxSimpleTriangleMesh@physx@@QEAA@XZ", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(PxSimpleTriangleMesh* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Constructor()
        {
            fixed (PxSimpleTriangleMesh* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?setToDefault@PxSimpleTriangleMesh@physx@@QEAAXXZ", ExactSpelling = true)]
        private static extern void setToDefault_PInvoke(PxSimpleTriangleMesh* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void setToDefault()
        {
            fixed (PxSimpleTriangleMesh* @this = &this)
            { setToDefault_PInvoke(@this); }
        }

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?isValid@PxSimpleTriangleMesh@physx@@QEBA_NXZ", ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        private static extern bool isValid_PInvoke(PxSimpleTriangleMesh* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe bool isValid()
        {
            fixed (PxSimpleTriangleMesh* @this = &this)
            { return isValid_PInvoke(@this); }
        }
    }
}
