// This file was automatically generated by Biohazrd and should not be modified by hand!
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 8)]
public unsafe partial struct PxTolerancesScale
{
    [FieldOffset(0)] public float length;

    [FieldOffset(4)] public float speed;

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxTolerancesScale@physx@@QEAA@XZ", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(PxTolerancesScale* @this);

    public unsafe void Constructor()
    {
        fixed (PxTolerancesScale* @this = &this)
        { Constructor_PInvoke(@this); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?isValid@PxTolerancesScale@physx@@QEBA_NXZ", ExactSpelling = true)]
    [return: MarshalAs(UnmanagedType.I1)]
    private static extern bool isValid_PInvoke(PxTolerancesScale* @this);

    public unsafe bool isValid()
    {
        fixed (PxTolerancesScale* @this = &this)
        { return isValid_PInvoke(@this); }
    }
}
