// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System;

namespace PhysX
{
    [Flags]
    public enum PxTriggerPairFlags : byte
    {
        eREMOVED_SHAPE_TRIGGER = 1,
        eREMOVED_SHAPE_OTHER = 2,
        eNEXT_FREE = 4
    }
}
