// This file was automatically generated by Biohazrd and should not be modified by hand!
using System;

[Flags]
public enum PxTriggerPairFlags : byte
{
    eREMOVED_SHAPE_TRIGGER = 1,
    eREMOVED_SHAPE_OTHER = 2,
    eNEXT_FREE = 4
}
