// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace PhysX
{
    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public unsafe partial struct PxUserControllerHitReport
    {
        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void onShapeHit(PxControllerShapeHit* hit)
        {
            fixed (PxUserControllerHitReport* @this = &this)
            { VirtualMethodTablePointer->onShapeHit(@this, hit); }
        }

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void onControllerHit(PxControllersHit* hit)
        {
            fixed (PxUserControllerHitReport* @this = &this)
            { VirtualMethodTablePointer->onControllerHit(@this, hit); }
        }

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void onObstacleHit(PxControllerObstacleHit* hit)
        {
            fixed (PxUserControllerHitReport* @this = &this)
            { VirtualMethodTablePointer->onObstacleHit(@this, hit); }
        }

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Destructor()
        {
            fixed (PxUserControllerHitReport* @this = &this)
            { VirtualMethodTablePointer->__DeletingDestructorPointer(@this); }
        }

        [FieldOffset(0)] public VirtualMethodTable* VirtualMethodTablePointer;

        [StructLayout(LayoutKind.Sequential)]
        public unsafe struct VirtualMethodTable
        {
            /// <summary>Virtual method pointer for `onShapeHit`</summary>
            public delegate* unmanaged[Cdecl]<PxUserControllerHitReport*, PxControllerShapeHit*, void> onShapeHit;
            /// <summary>Virtual method pointer for `onControllerHit`</summary>
            public delegate* unmanaged[Cdecl]<PxUserControllerHitReport*, PxControllersHit*, void> onControllerHit;
            /// <summary>Virtual method pointer for `onObstacleHit`</summary>
            public delegate* unmanaged[Cdecl]<PxUserControllerHitReport*, PxControllerObstacleHit*, void> onObstacleHit;
            /// <summary>Virtual method pointer for `~PxUserControllerHitReport`</summary>
            public delegate* unmanaged[Cdecl]<PxUserControllerHitReport*, void> __DeletingDestructorPointer;
        }
    }
}
