// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using Mochi.PhysX.Infrastructure;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.PhysX
{
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe partial struct PxVehicleClutchData
    {
        [DllImport("Mochi.PhysX.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper197", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(PxVehicleClutchData* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Constructor()
        {
            fixed (PxVehicleClutchData* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [FieldOffset(0)] public float mStrength;

        [FieldOffset(4)] public PxVehicleClutchAccuracyMode mAccuracyMode;

        [FieldOffset(8)] public uint mEstimateIterations;

        [FieldOffset(12)] public ConstantArray_physx__UNICODE_003A____UNICODE_003A__PxU8_4 mPad;

        [DllImport("Mochi.PhysX.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper198", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(PxVehicleClutchData* @this, PxEMPTY arg0);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Constructor(PxEMPTY arg0)
        {
            fixed (PxVehicleClutchData* @this = &this)
            { Constructor_PInvoke(@this, arg0); }
        }
    }
}
