// This file was automatically generated by Biohazrd and should not be modified by hand!
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 16)]
public unsafe partial struct PxVehicleWheelQueryResult
{
    [FieldOffset(0)] public PxWheelQueryResult* wheelQueryResults;

    [FieldOffset(8)] public uint nbWheelQueryResults;
}
