// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace PhysX
{
    [StructLayout(LayoutKind.Explicit, Size = 112)]
    public unsafe partial struct PxVehicleEngineData
    {
        public const int eMAX_NB_ENGINE_TORQUE_CURVE_ENTRIES = 8;

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxVehicleEngineData@physx@@QEAA@XZ", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(PxVehicleEngineData* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Constructor()
        {
            fixed (PxVehicleEngineData* @this = &this)
            { Constructor_PInvoke(@this); }
        }

        [FieldOffset(0)] public /* Failed to emit TranslatedNormalField mTorqueCurve: Failed to resolve `Ref resolved by PxFixedSizeLookupTable` during emit time. */
        int mTorqueCurve;

        [FieldOffset(80)] public float mMOI;

        [FieldOffset(84)] public float mPeakTorque;

        [FieldOffset(88)] public float mMaxOmega;

        [FieldOffset(92)] public float mDampingRateFullThrottle;

        [FieldOffset(96)] public float mDampingRateZeroThrottleClutchEngaged;

        [FieldOffset(100)] public float mDampingRateZeroThrottleClutchDisengaged;

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?getRecipMOI@PxVehicleEngineData@physx@@QEBAMXZ", ExactSpelling = true)]
        private static extern float getRecipMOI_PInvoke(PxVehicleEngineData* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe float getRecipMOI()
        {
            fixed (PxVehicleEngineData* @this = &this)
            { return getRecipMOI_PInvoke(@this); }
        }

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?getRecipMaxOmega@PxVehicleEngineData@physx@@QEBAMXZ", ExactSpelling = true)]
        private static extern float getRecipMaxOmega_PInvoke(PxVehicleEngineData* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe float getRecipMaxOmega()
        {
            fixed (PxVehicleEngineData* @this = &this)
            { return getRecipMaxOmega_PInvoke(@this); }
        }

        [FieldOffset(104)] public float mRecipMOI;

        [FieldOffset(108)] public float mRecipMaxOmega;

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?isValid@PxVehicleEngineData@physx@@AEBA_NXZ", ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        private static extern bool isValid_PInvoke(PxVehicleEngineData* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe bool isValid()
        {
            fixed (PxVehicleEngineData* @this = &this)
            { return isValid_PInvoke(@this); }
        }

        [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxVehicleEngineData@physx@@QEAA@W4PxEMPTY@1@@Z", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(PxVehicleEngineData* @this, PxEMPTY arg0);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public unsafe void Constructor(PxEMPTY arg0)
        {
            fixed (PxVehicleEngineData* @this = &this)
            { Constructor_PInvoke(@this, arg0); }
        }
    }
}
