// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using Mochi.PhysX.Infrastructure;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.PhysX
{
    [StructLayout(LayoutKind.Explicit, Size = 832)]
    public unsafe partial struct PxVehicleDriveTank
    {
        [FieldOffset(0)] public PxVehicleDrive Base;

        [DllImport("Mochi.PhysX.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?allocate@PxVehicleDriveTank@physx@@SAPEAV12@I@Z", ExactSpelling = true)]
        public static extern PxVehicleDriveTank* allocate(uint nbWheels);

        [DllImport("Mochi.PhysX.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?free@PxVehicleDriveTank@physx@@QEAAXXZ", ExactSpelling = true)]
        private static extern void free_PInvoke(PxVehicleDriveTank* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void free()
        {
            fixed (PxVehicleDriveTank* @this = &this)
            { free_PInvoke(@this); }
        }

        [DllImport("Mochi.PhysX.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?setup@PxVehicleDriveTank@physx@@QEAAXPEAVPxPhysics@2@PEAVPxRigidDynamic@2@AEBVPxVehicleWheelsSimData@2@AEBVPxVehicleDriveSimData@2@I@Z", ExactSpelling = true)]
        private static extern void setup_PInvoke(PxVehicleDriveTank* @this, PxPhysics* physics, PxRigidDynamic* vehActor, PxVehicleWheelsSimData* wheelsData, PxVehicleDriveSimData* driveData, uint nbDrivenWheels);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void setup(PxPhysics* physics, PxRigidDynamic* vehActor, PxVehicleWheelsSimData* wheelsData, PxVehicleDriveSimData* driveData, uint nbDrivenWheels)
        {
            fixed (PxVehicleDriveTank* @this = &this)
            { setup_PInvoke(@this, physics, vehActor, wheelsData, driveData, nbDrivenWheels); }
        }

        [DllImport("Mochi.PhysX.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?create@PxVehicleDriveTank@physx@@SAPEAV12@PEAVPxPhysics@2@PEAVPxRigidDynamic@2@AEBVPxVehicleWheelsSimData@2@AEBVPxVehicleDriveSimData@2@I@Z", ExactSpelling = true)]
        public static extern PxVehicleDriveTank* create(PxPhysics* physics, PxRigidDynamic* vehActor, PxVehicleWheelsSimData* wheelsData, PxVehicleDriveSimData* driveData, uint nbDrivenWheels);

        [DllImport("Mochi.PhysX.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?setDriveModel@PxVehicleDriveTank@physx@@QEAAXW4Enum@PxVehicleDriveTankControlModel@2@@Z", ExactSpelling = true)]
        private static extern void setDriveModel_PInvoke(PxVehicleDriveTank* @this, PxVehicleDriveTankControlModel driveModel);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void setDriveModel(PxVehicleDriveTankControlModel driveModel)
        {
            fixed (PxVehicleDriveTank* @this = &this)
            { setDriveModel_PInvoke(@this, driveModel); }
        }

        [DllImport("Mochi.PhysX.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?getDriveModel@PxVehicleDriveTank@physx@@QEBA?AW4Enum@PxVehicleDriveTankControlModel@2@XZ", ExactSpelling = true)]
        private static extern PxVehicleDriveTankControlModel getDriveModel_PInvoke(PxVehicleDriveTank* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public PxVehicleDriveTankControlModel getDriveModel()
        {
            fixed (PxVehicleDriveTank* @this = &this)
            { return getDriveModel_PInvoke(@this); }
        }

        [DllImport("Mochi.PhysX.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?setToRestState@PxVehicleDriveTank@physx@@QEAAXXZ", ExactSpelling = true)]
        private static extern void setToRestState_PInvoke(PxVehicleDriveTank* @this);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void setToRestState()
        {
            fixed (PxVehicleDriveTank* @this = &this)
            { setToRestState_PInvoke(@this); }
        }

        [FieldOffset(288)] public PxVehicleDriveSimData mDriveSimData;

        [FieldOffset(816)] public PxVehicleDriveTankControlModel mDriveModel;

        [FieldOffset(820)] public ConstantArray_physx__UNICODE_003A____UNICODE_003A__PxU32_3 mPad;

        [DllImport("Mochi.PhysX.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "__InlineHelper219", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(PxVehicleDriveTank* @this, PxBaseFlags* baseFlags);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Constructor(PxBaseFlags* baseFlags)
        {
            fixed (PxVehicleDriveTank* @this = &this)
            { Constructor_PInvoke(@this, baseFlags); }
        }

        [DllImport("Mochi.PhysX.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?createObject@PxVehicleDriveTank@physx@@SAPEAV12@AEAPEAEAEAVPxDeserializationContext@2@@Z", ExactSpelling = true)]
        public static extern PxVehicleDriveTank* createObject(byte** address, PxDeserializationContext* context);

        [DllImport("Mochi.PhysX.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?getBinaryMetaData@PxVehicleDriveTank@physx@@SAXAEAVPxOutputStream@2@@Z", ExactSpelling = true)]
        public static extern void getBinaryMetaData(PxOutputStream* stream);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public byte* getConcreteTypeName()
        {
            fixed (PxVehicleDriveTank* @this = &this)
            { return VirtualMethodTablePointer->getConcreteTypeName(@this); }
        }

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool isKindOf(byte* name)
        {
            fixed (PxVehicleDriveTank* @this = &this)
            { return VirtualMethodTablePointer->isKindOf(@this, name); }
        }

        [FieldOffset(0)] public VirtualMethodTable* VirtualMethodTablePointer;

        [StructLayout(LayoutKind.Sequential)]
        public unsafe struct VirtualMethodTable
        {
            /// <summary>Virtual method pointer for `release`</summary>
            public delegate* unmanaged[Cdecl]<PxVehicleDriveTank*, void> release;
            /// <summary>Virtual method pointer for `getConcreteTypeName`</summary>
            public delegate* unmanaged[Cdecl]<PxVehicleDriveTank*, byte*> getConcreteTypeName;
            /// <summary>Virtual method pointer for `isReleasable`</summary>
            public delegate* unmanaged[Cdecl]<PxVehicleDriveTank*, NativeBoolean> isReleasable;
            /// <summary>Virtual method pointer for `~PxVehicleDriveTank`</summary>
            public void* __DeletingDestructorPointer;
            /// <summary>Virtual method pointer for `isKindOf`</summary>
            public delegate* unmanaged[Cdecl]<PxVehicleDriveTank*, byte*, NativeBoolean> isKindOf;
            /// <summary>Virtual method pointer for `init`</summary>
            public void* init;
            /// <summary>Virtual method pointer for `requiresObjects`</summary>
            public delegate* unmanaged[Cdecl]<PxVehicleDriveTank*, PxProcessPxBaseCallback*, void> requiresObjects;
            /// <summary>Virtual method pointer for `preExportDataReset`</summary>
            public delegate* unmanaged[Cdecl]<PxVehicleDriveTank*, void> preExportDataReset;
            /// <summary>Virtual method pointer for `exportExtraData`</summary>
            public delegate* unmanaged[Cdecl]<PxVehicleDriveTank*, PxSerializationContext*, void> exportExtraData;
        }
    }
}
