// This file was automatically generated by Biohazrd and should not be modified by hand!
using System.ComponentModel;
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 8)]
public unsafe partial struct PxVec2
{
    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxVec2@physx@@QEAA@XZ", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(PxVec2* @this);

    public unsafe void Constructor()
    {
        fixed (PxVec2* @this = &this)
        { Constructor_PInvoke(@this); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxVec2@physx@@QEAA@W4PxZERO@1@@Z", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(PxVec2* @this, PxZERO r);

    public unsafe void Constructor(PxZERO r)
    {
        fixed (PxVec2* @this = &this)
        { Constructor_PInvoke(@this, r); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxVec2@physx@@QEAA@M@Z", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(PxVec2* @this, float a);

    public unsafe void Constructor(float a)
    {
        fixed (PxVec2* @this = &this)
        { Constructor_PInvoke(@this, a); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxVec2@physx@@QEAA@MM@Z", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(PxVec2* @this, float nx, float ny);

    public unsafe void Constructor(float nx, float ny)
    {
        fixed (PxVec2* @this = &this)
        { Constructor_PInvoke(@this, nx, ny); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxVec2@physx@@QEAA@AEBV01@@Z", ExactSpelling = true)]
    private static extern void Constructor_PInvoke(PxVec2* @this, PxVec2* v);

    public unsafe void Constructor(PxVec2* v)
    {
        fixed (PxVec2* @this = &this)
        { Constructor_PInvoke(@this, v); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??4PxVec2@physx@@QEAAAEAV01@AEBV01@@Z", ExactSpelling = true)]
    private static extern PxVec2* operator_Equal_PInvoke(PxVec2* @this, PxVec2* p);

    public unsafe PxVec2* operator_Equal(PxVec2* p)
    {
        fixed (PxVec2* @this = &this)
        { return operator_Equal_PInvoke(@this, p); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??APxVec2@physx@@QEAAAEAMH@Z", ExactSpelling = true)]
    private static extern float* operator_Subscript_PInvoke(PxVec2* @this, int index);

    public unsafe float* operator_Subscript(int index)
    {
        fixed (PxVec2* @this = &this)
        { return operator_Subscript_PInvoke(@this, index); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??APxVec2@physx@@QEBAAEBMH@Z", ExactSpelling = true)]
    private static extern float* operator_Subscript_Const_PInvoke(PxVec2* @this, int index);

    [EditorBrowsable(EditorBrowsableState.Never)]
    public unsafe float* operator_Subscript_Const(int index)
    {
        fixed (PxVec2* @this = &this)
        { return operator_Subscript_Const_PInvoke(@this, index); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??8PxVec2@physx@@QEBA_NAEBV01@@Z", ExactSpelling = true)]
    private static extern bool operator_EqualEqual_PInvoke(PxVec2* @this, PxVec2* v);

    public unsafe bool operator_EqualEqual(PxVec2* v)
    {
        fixed (PxVec2* @this = &this)
        { return operator_EqualEqual_PInvoke(@this, v); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??9PxVec2@physx@@QEBA_NAEBV01@@Z", ExactSpelling = true)]
    private static extern bool operator_ExclaimEqual_PInvoke(PxVec2* @this, PxVec2* v);

    public unsafe bool operator_ExclaimEqual(PxVec2* v)
    {
        fixed (PxVec2* @this = &this)
        { return operator_ExclaimEqual_PInvoke(@this, v); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?isZero@PxVec2@physx@@QEBA_NXZ", ExactSpelling = true)]
    private static extern bool isZero_PInvoke(PxVec2* @this);

    public unsafe bool isZero()
    {
        fixed (PxVec2* @this = &this)
        { return isZero_PInvoke(@this); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?isFinite@PxVec2@physx@@QEBA_NXZ", ExactSpelling = true)]
    private static extern bool isFinite_PInvoke(PxVec2* @this);

    public unsafe bool isFinite()
    {
        fixed (PxVec2* @this = &this)
        { return isFinite_PInvoke(@this); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?isNormalized@PxVec2@physx@@QEBA_NXZ", ExactSpelling = true)]
    private static extern bool isNormalized_PInvoke(PxVec2* @this);

    public unsafe bool isNormalized()
    {
        fixed (PxVec2* @this = &this)
        { return isNormalized_PInvoke(@this); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?magnitudeSquared@PxVec2@physx@@QEBAMXZ", ExactSpelling = true)]
    private static extern float magnitudeSquared_PInvoke(PxVec2* @this);

    public unsafe float magnitudeSquared()
    {
        fixed (PxVec2* @this = &this)
        { return magnitudeSquared_PInvoke(@this); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?magnitude@PxVec2@physx@@QEBAMXZ", ExactSpelling = true)]
    private static extern float magnitude_PInvoke(PxVec2* @this);

    public unsafe float magnitude()
    {
        fixed (PxVec2* @this = &this)
        { return magnitude_PInvoke(@this); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??GPxVec2@physx@@QEBA?AV01@XZ", ExactSpelling = true)]
    private static extern void operator_Minus_PInvoke(PxVec2* @this, out PxVec2 __returnBuffer);

    public unsafe PxVec2 operator_Minus()
    {
        fixed (PxVec2* @this = &this)
        {
            PxVec2 __returnBuffer;
            operator_Minus_PInvoke(@this, out __returnBuffer);
            return __returnBuffer;
        }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??HPxVec2@physx@@QEBA?AV01@AEBV01@@Z", ExactSpelling = true)]
    private static extern void operator_Plus_PInvoke(PxVec2* @this, out PxVec2 __returnBuffer, PxVec2* v);

    public unsafe PxVec2 operator_Plus(PxVec2* v)
    {
        fixed (PxVec2* @this = &this)
        {
            PxVec2 __returnBuffer;
            operator_Plus_PInvoke(@this, out __returnBuffer, v);
            return __returnBuffer;
        }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??GPxVec2@physx@@QEBA?AV01@AEBV01@@Z", ExactSpelling = true)]
    private static extern void operator_Minus_PInvoke(PxVec2* @this, out PxVec2 __returnBuffer, PxVec2* v);

    public unsafe PxVec2 operator_Minus(PxVec2* v)
    {
        fixed (PxVec2* @this = &this)
        {
            PxVec2 __returnBuffer;
            operator_Minus_PInvoke(@this, out __returnBuffer, v);
            return __returnBuffer;
        }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??DPxVec2@physx@@QEBA?AV01@M@Z", ExactSpelling = true)]
    private static extern void operator_Star_PInvoke(PxVec2* @this, out PxVec2 __returnBuffer, float f);

    public unsafe PxVec2 operator_Star(float f)
    {
        fixed (PxVec2* @this = &this)
        {
            PxVec2 __returnBuffer;
            operator_Star_PInvoke(@this, out __returnBuffer, f);
            return __returnBuffer;
        }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??KPxVec2@physx@@QEBA?AV01@M@Z", ExactSpelling = true)]
    private static extern void operator_Slash_PInvoke(PxVec2* @this, out PxVec2 __returnBuffer, float f);

    public unsafe PxVec2 operator_Slash(float f)
    {
        fixed (PxVec2* @this = &this)
        {
            PxVec2 __returnBuffer;
            operator_Slash_PInvoke(@this, out __returnBuffer, f);
            return __returnBuffer;
        }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??YPxVec2@physx@@QEAAAEAV01@AEBV01@@Z", ExactSpelling = true)]
    private static extern PxVec2* operator_PlusEqual_PInvoke(PxVec2* @this, PxVec2* v);

    public unsafe PxVec2* operator_PlusEqual(PxVec2* v)
    {
        fixed (PxVec2* @this = &this)
        { return operator_PlusEqual_PInvoke(@this, v); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??ZPxVec2@physx@@QEAAAEAV01@AEBV01@@Z", ExactSpelling = true)]
    private static extern PxVec2* operator_MinusEqual_PInvoke(PxVec2* @this, PxVec2* v);

    public unsafe PxVec2* operator_MinusEqual(PxVec2* v)
    {
        fixed (PxVec2* @this = &this)
        { return operator_MinusEqual_PInvoke(@this, v); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??XPxVec2@physx@@QEAAAEAV01@M@Z", ExactSpelling = true)]
    private static extern PxVec2* operator_StarEqual_PInvoke(PxVec2* @this, float f);

    public unsafe PxVec2* operator_StarEqual(float f)
    {
        fixed (PxVec2* @this = &this)
        { return operator_StarEqual_PInvoke(@this, f); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??_0PxVec2@physx@@QEAAAEAV01@M@Z", ExactSpelling = true)]
    private static extern PxVec2* operator_SlashEqual_PInvoke(PxVec2* @this, float f);

    public unsafe PxVec2* operator_SlashEqual(float f)
    {
        fixed (PxVec2* @this = &this)
        { return operator_SlashEqual_PInvoke(@this, f); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?dot@PxVec2@physx@@QEBAMAEBV12@@Z", ExactSpelling = true)]
    private static extern float dot_PInvoke(PxVec2* @this, PxVec2* v);

    public unsafe float dot(PxVec2* v)
    {
        fixed (PxVec2* @this = &this)
        { return dot_PInvoke(@this, v); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?getNormalized@PxVec2@physx@@QEBA?AV12@XZ", ExactSpelling = true)]
    private static extern void getNormalized_PInvoke(PxVec2* @this, out PxVec2 __returnBuffer);

    public unsafe PxVec2 getNormalized()
    {
        fixed (PxVec2* @this = &this)
        {
            PxVec2 __returnBuffer;
            getNormalized_PInvoke(@this, out __returnBuffer);
            return __returnBuffer;
        }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?normalize@PxVec2@physx@@QEAAMXZ", ExactSpelling = true)]
    private static extern float normalize_PInvoke(PxVec2* @this);

    public unsafe float normalize()
    {
        fixed (PxVec2* @this = &this)
        { return normalize_PInvoke(@this); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?multiply@PxVec2@physx@@QEBA?AV12@AEBV12@@Z", ExactSpelling = true)]
    private static extern void multiply_PInvoke(PxVec2* @this, out PxVec2 __returnBuffer, PxVec2* a);

    public unsafe PxVec2 multiply(PxVec2* a)
    {
        fixed (PxVec2* @this = &this)
        {
            PxVec2 __returnBuffer;
            multiply_PInvoke(@this, out __returnBuffer, a);
            return __returnBuffer;
        }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?minimum@PxVec2@physx@@QEBA?AV12@AEBV12@@Z", ExactSpelling = true)]
    private static extern void minimum_PInvoke(PxVec2* @this, out PxVec2 __returnBuffer, PxVec2* v);

    public unsafe PxVec2 minimum(PxVec2* v)
    {
        fixed (PxVec2* @this = &this)
        {
            PxVec2 __returnBuffer;
            minimum_PInvoke(@this, out __returnBuffer, v);
            return __returnBuffer;
        }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?minElement@PxVec2@physx@@QEBAMXZ", ExactSpelling = true)]
    private static extern float minElement_PInvoke(PxVec2* @this);

    public unsafe float minElement()
    {
        fixed (PxVec2* @this = &this)
        { return minElement_PInvoke(@this); }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?maximum@PxVec2@physx@@QEBA?AV12@AEBV12@@Z", ExactSpelling = true)]
    private static extern void maximum_PInvoke(PxVec2* @this, out PxVec2 __returnBuffer, PxVec2* v);

    public unsafe PxVec2 maximum(PxVec2* v)
    {
        fixed (PxVec2* @this = &this)
        {
            PxVec2 __returnBuffer;
            maximum_PInvoke(@this, out __returnBuffer, v);
            return __returnBuffer;
        }
    }

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "?maxElement@PxVec2@physx@@QEBAMXZ", ExactSpelling = true)]
    private static extern float maxElement_PInvoke(PxVec2* @this);

    public unsafe float maxElement()
    {
        fixed (PxVec2* @this = &this)
        { return maxElement_PInvoke(@this); }
    }

    [FieldOffset(0)] public float x;

    [FieldOffset(4)] public float y;

    [DllImport("TODO.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??Dphysx@@YA?AVPxVec2@0@MAEBV10@@Z", ExactSpelling = true)]
    public static extern void operator_Star(out PxVec2 __returnBuffer, float f, PxVec2* v);
}
