// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System;

namespace PhysX
{
    [Flags]
    public enum PxVehicleWheelsSimFlags : uint
    {
        eLIMIT_SUSPENSION_EXPANSION_VELOCITY = 1
    }
}
