// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System;

namespace Mochi.PhysX
{
    [Flags]
    public enum PxArticulationFlags : byte
    {
        eFIX_BASE = 1,
        eDRIVE_LIMITS_ARE_FORCES = 2
    }
}
