// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.PhysX
{
    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public unsafe partial struct PxBroadPhaseCallback
    {
        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Destructor()
        {
            fixed (PxBroadPhaseCallback* @this = &this)
            { VirtualMethodTablePointer->__DeletingDestructorPointer(@this); }
        }

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void onObjectOutOfBounds(PxShape* shape, PxActor* actor)
        {
            fixed (PxBroadPhaseCallback* @this = &this)
            { VirtualMethodTablePointer->onObjectOutOfBounds_1(@this, shape, actor); }
        }

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void onObjectOutOfBounds(PxAggregate* aggregate)
        {
            fixed (PxBroadPhaseCallback* @this = &this)
            { VirtualMethodTablePointer->onObjectOutOfBounds_0(@this, aggregate); }
        }

        [FieldOffset(0)] public VirtualMethodTable* VirtualMethodTablePointer;

        [StructLayout(LayoutKind.Sequential)]
        public unsafe struct VirtualMethodTable
        {
            /// <summary>Virtual method pointer for `~PxBroadPhaseCallback`</summary>
            public delegate* unmanaged[Cdecl]<PxBroadPhaseCallback*, void> __DeletingDestructorPointer;
            /// <summary>Virtual method pointer for `onObjectOutOfBounds`</summary>
            public delegate* unmanaged[Cdecl]<PxBroadPhaseCallback*, PxAggregate*, void> onObjectOutOfBounds_0;
            /// <summary>Virtual method pointer for `onObjectOutOfBounds`</summary>
            public delegate* unmanaged[Cdecl]<PxBroadPhaseCallback*, PxShape*, PxActor*, void> onObjectOutOfBounds_1;
        }
    }
}
