// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.PhysX
{
    [StructLayout(LayoutKind.Explicit, Size = 8)]
    public unsafe partial struct PxConstraintAllocator
    {
        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public byte* reserveConstraintData(uint byteSize)
        {
            fixed (PxConstraintAllocator* @this = &this)
            { return VirtualMethodTablePointer->reserveConstraintData(@this, byteSize); }
        }

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public byte* reserveFrictionData(uint byteSize)
        {
            fixed (PxConstraintAllocator* @this = &this)
            { return VirtualMethodTablePointer->reserveFrictionData(@this, byteSize); }
        }

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Destructor()
        {
            fixed (PxConstraintAllocator* @this = &this)
            { VirtualMethodTablePointer->__DeletingDestructorPointer(@this); }
        }

        [FieldOffset(0)] public VirtualMethodTable* VirtualMethodTablePointer;

        [StructLayout(LayoutKind.Sequential)]
        public unsafe struct VirtualMethodTable
        {
            /// <summary>Virtual method pointer for `reserveConstraintData`</summary>
            public delegate* unmanaged[Cdecl]<PxConstraintAllocator*, uint, byte*> reserveConstraintData;
            /// <summary>Virtual method pointer for `reserveFrictionData`</summary>
            public delegate* unmanaged[Cdecl]<PxConstraintAllocator*, uint, byte*> reserveFrictionData;
            /// <summary>Virtual method pointer for `~PxConstraintAllocator`</summary>
            public delegate* unmanaged[Cdecl]<PxConstraintAllocator*, void> __DeletingDestructorPointer;
        }
    }
}
