// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System;

namespace Mochi.PhysX
{
    [Flags]
    public enum PxConstraintFlags : ushort
    {
        eBROKEN = 1,
        ePROJECT_TO_ACTOR0 = 2,
        ePROJECT_TO_ACTOR1 = 4,
        ePROJECTION = 6,
        eCOLLISION_ENABLED = 8,
        eVISUALIZATION = 16,
        eDRIVE_LIMITS_ARE_FORCES = 32,
        eIMPROVED_SLERP = 128,
        eDISABLE_PREPROCESSING = 256,
        eENABLE_EXTENDED_LIMITS = 512,
        eGPU_COMPATIBLE = 1024
    }
}
