// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Mochi.PhysX
{
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public unsafe partial struct PxDefaultMemoryOutputStream
    {
        [FieldOffset(0)] public PxOutputStream Base;

        [DllImport("Mochi.PhysX.Native.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "??0PxDefaultMemoryOutputStream@physx@@QEAA@AEAVPxAllocatorCallback@1@@Z", ExactSpelling = true)]
        private static extern void Constructor_PInvoke(PxDefaultMemoryOutputStream* @this, PxAllocatorCallback* allocator);

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public PxDefaultMemoryOutputStream(PxAllocatorCallback* allocator)
        {
            fixed (PxDefaultMemoryOutputStream* @this = &this)
            { Constructor_PInvoke(@this, allocator); }
        }

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Destructor()
        {
            fixed (PxDefaultMemoryOutputStream* @this = &this)
            { VirtualMethodTablePointer->__DeletingDestructorPointer(@this); }
        }

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public uint write(void* src, uint count)
        {
            fixed (PxDefaultMemoryOutputStream* @this = &this)
            { return VirtualMethodTablePointer->write(@this, src, count); }
        }

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public uint getSize()
        {
            fixed (PxDefaultMemoryOutputStream* @this = &this)
            { return VirtualMethodTablePointer->getSize(@this); }
        }

        [DebuggerStepThrough, DebuggerHidden]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public byte* getData()
        {
            fixed (PxDefaultMemoryOutputStream* @this = &this)
            { return VirtualMethodTablePointer->getData(@this); }
        }

        [FieldOffset(8)] public PxAllocatorCallback* mAllocator;

        [FieldOffset(16)] public byte* mData;

        [FieldOffset(24)] public uint mSize;

        [FieldOffset(28)] public uint mCapacity;

        [FieldOffset(0)] public VirtualMethodTable* VirtualMethodTablePointer;

        [StructLayout(LayoutKind.Sequential)]
        public unsafe struct VirtualMethodTable
        {
            /// <summary>Virtual method pointer for `write`</summary>
            public delegate* unmanaged[Cdecl]<PxDefaultMemoryOutputStream*, void*, uint, uint> write;
            /// <summary>Virtual method pointer for `~PxDefaultMemoryOutputStream`</summary>
            public delegate* unmanaged[Cdecl]<PxDefaultMemoryOutputStream*, void> __DeletingDestructorPointer;
            /// <summary>Virtual method pointer for `getSize`</summary>
            public delegate* unmanaged[Cdecl]<PxDefaultMemoryOutputStream*, uint> getSize;
            /// <summary>Virtual method pointer for `getData`</summary>
            public delegate* unmanaged[Cdecl]<PxDefaultMemoryOutputStream*, byte*> getData;
        }
    }
}
